### PR TITLE
Fix for dd() and dump()

### PR DESCRIPTION
**Pull request by antonioribeiro**

### CODE REVIEW

**Comment by antonioribeiro** [comment]
To fix [this issue](https://github.com/tightenco/collect/issues/64)

**Comment by mattstauffer** [comment]
Thanks! This fixes the `dump()` issue and paves the way for fixing the `dd()` issue. 👌

**Comment by mattstauffer** [comment]
This will go out with whichever our next build is.

**Comment by antonioribeiro** [comment]
Sent this PR to Framework:

https://github.com/laravel/framework/pull/22036

Fixing 2 problems:

1) [bug] dd() & dump() were not behaving the same way.

2) [design] Collection was not supposed to call (depend on) that particular "external" helper, since it already had its own  dumper(), and it was just a matter of calling it and add the `die` instruction.

**Comment by mattstauffer** [comment]
👍🏻 Smart

**Pull request merged**
