### PR TITLE
Laravel 5.5.45 changes

### PR DESCRIPTION
**Pull request by anthonyterrell**
This pull request brings the `laravel-5.5-ongoing` branch current as well as updates Collect to `5.5.45`.

1. Added `upgrade.sh`
1. Added `stubs` directory

### CODE REVIEW

**Comment by anthonyterrell** [comment]
@mattstauffer for your review when you have time.

**Comment by antonioribeiro** [comment]
@anthonyterrell, were you able to use upgrade.sh to do this upgrade?

**Comment by anthonyterrell** [comment]
> @anthonyterrell, were you able to use upgrade.sh to do this upgrade?

hey @antonioribeiro, yes I was able to. I ran `./upgrade.sh 5.5.45`

**Comment by mattstauffer** [comment]
Tests run for me. ¯\(°_o)/¯ let's go!

**Pull request merged**
