### PR TITLE
Allow Symfony <4.0

### PR DESCRIPTION
**Pull request by antonioribeiro**
Fix for https://github.com/tightenco/collect/issues

### CODE REVIEW

**Comment by mathieutu** [comment]
https://github.com/tightenco/collect/issues/83

**Comment by mattstauffer** [comment]
@antonioribeiro Have you tested that the methods are available as expected on the older verisons? I assume so, but just wanted to check :)

**Comment by antonioribeiro** [comment]
@mattstauffer, tested until I found a version where `dd()` was working. On 3.1.0, for instance, it was not working. But I did not tested for `dump()`, because `dd()` was supposed to be `dump()` and die, but that may not be true. :/

**Comment by mattstauffer** [comment]
@antonioribeiro ok sweet i'll merge this then go see if i can check dump as well and if it fails I'll modify it. Thanks!

**Comment by antonioribeiro** [comment]
I just checked both, they work fine. But I wasn't able to test it using the commit history of the master branch, only using tag v5.6.0. The master branch is ~30 commits ahead.

**Comment by mattstauffer** [comment]
@antonioribeiro I just tested using the master and it was good. 🙌

**Pull request merged**
